
env = Environment()

env.MergeFlags({'CCFLAGS' : ['-O3', '-Wall', '-g', '-std=gnu99'],
                'LFLAGS' : ['-lz -lm'],
                'LIBS' : ['z', 'm']})


# build genome library
Export('env')

libgenome = SConscript(['lib/SConscript'])

env.MergeFlags({'LIBPATH' : ['#/lib'],
                'CPPPATH' : ['#/lib']})

Export('libgenome')


# build programs
SConscript(['program/SConscript'])


